### ISSUE TITLE
Rvalue parameters

### ISSUE THREAD

**Issue by JuergenMueller** [jll63/yomm2#1]
Declaring methods with rvalue parameters doesn't seem to work.
E.g. something like,

```c++
declare_method(float, my_function, (virtual_<matrix&&>));
```
produces a rather long error message (using g++ 7.2) with repeated error messages saying:
`error: ‘<anonymous>’ has incomplete type`

**Comment by jll63** [comment]
You fed virtual_<> something other than what the doc says it accepts. But indeed this should work. Probably I can do that later today.

**Comment by jll63** [comment]
Added support for rvalue references.
